stages:
  download_data:
    cmd: python processed_data/preprocess_data.py
    deps:
    - processed_data/preprocess_data.py
    - processd_data/reddit.csv
    outs:
    - processd_data/ml_reddit_node.npy
    - processd_data/ml_reddit.csv
    - processd_data/ml_reddit.npy
  trains:
    cmd: python train_link_prediction.py --dataset_name reddit --model_name GraphMixer --num_runs 2 --gpu 0
    deps:
    - train_link_prediction.py
    - processed_data/ml_reddit_node.npy
    - processed_data/ml_reddit.csv
    - processed_data/ml_reddit.npy
    outs:
    - logs
    - saved_models
metrics:
  - dvclive/metrics.json
