name: CML & DVC
on: 
  push: 
      branches:
      - experiment
      paths:
        - train_link_prediction.py
        - model/*
        - utils/*
        - data/*
        - .github/workflows/cml.yaml
jobs:
  train-and-report:
    runs-on: ubuntu-latest
    # container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - uses: iterative/setup-cml@v2
      - uses: iterative/setup-dvc@v1
      - name: Train model
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          pip install -r requirements.txt  # Install dependencies
          dvc pull data --run-cache        # Pull data & run-cache from S3
          dvc repro                        # Reproduce pipeline
      - name: Create CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          dvc remote modify --local mybucket \
                    access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          dvc remote modify --local mybucket \
                    secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          dvc push -r mybucket
          dvc metrics show >> report.md

          cml comment create report.md
      - name: Commit changes during running workflow
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Commit changes in dvc.lock
          branch: experiment
          file_pattern: dvc.lock saved_model/ dvclive/